- name: File locks tests {{ accessMode }}
  block:
  - name: File locks tests
    include_tasks: file-lock-test.yaml 
  rescue:
    - debug:
        msg: "File locks tests - FAILED"
  vars:
    accessMode: ReadWriteMany


